# docker compose will automaticlly run and build from source
version: "3.5"
services:
  # build web-fe image and run the container 
  web-fe: 
    build: .
    command: python app.py
    ports:
      - target: 5000
        published: 5000
    networks:
      - counter-net
    volumes:
      - type: volume
        source: counter-vol
        target: /code
  # build the container from the image pull from docker-hub
  redis:
    image: "redis:alpine"
    networks:
      counter-net:

networks:
  counter-net:

volumes:
  counter-vol: